
baseURL = 'https://blog.alaerts-schelles.be/'
languageCode = 'nl'
defaultContentLanguage = 'nl'
title = 'Het Hoge Noorden'
theme = 'hugo-PaperMod'

[params]
  ShowReadingTime = true
  ShowToc = true
  DateFormat = "01-05-2025"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
