
baseURL = 'https://blog.alaerts-schelles.be/'
languageCode = 'nl'
defaultContentLanguage = 'nl'
title = 'Het Hoge Noorden'
theme = 'hugo-PaperMod'
googleAnalytics = "G-F5X5PM44HF"

[params]
  ShowReadingTime = true
  ShowToc = true
  DateFormat = "02-01-2006"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
